### ISSUE TITLE
Missed "period" at the end of one sentence.

### ISSUE THREAD

**Issue by lst1975** [vmware/ml-ops-platform-for-vsphere#42]
### Describe the bug

You can get the source code of the example from here

### Reproduction steps

You can get the source code of the example from here**.**

### Expected behavior

You can get the source code of the example from here**.**

**Comment by arielzhu0512** [comment]
Could you please be a little bit more specific here? For example, in which section? (I found this sentence in "Advanced Features -> Bitfusion" section, but there is a period there. I am not sure if that is the sentence you were specifying. If so, this problem might have been already fixed. Otherwise, could you please specify the section of this issue?)

**Comment by lst1975** [comment]
Describe the bug

You can get the source code of the example from here

Reproduction steps

You can get the source code of the example from here**.**

Expected behavior

You can get the source code of the example from here**.**




---Original---
From: ***@***.***&gt;
Date: Thu, Mar 9, 2023 21:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vmware/ml-ops-platform-for-vsphere] Missed "period" at the endof one sentence. (Issue #42)




 
Could you please be a little bit more specific here? For example, in which section? (I found this sentence in "Advanced Features -&gt; Bitfusion" section, but there is a period there. I am not sure if that is the sentence you were specifying. If so, this problem might have been already fixed. Otherwise, could you please specify the section of this issue?)
